### ISSUE TITLE
Verify that the credential resolver works with manifest lists and indices

### ISSUE THREAD

**Issue by samuelkarp** [awslabs/amazon-ecr-containerd-resolver#12]
Support for manifest lists and indices in ECR is now available: https://github.com/aws/containers-roadmap/issues/505#issuecomment-620871790.  This resolver needs to be tested to ensure that it works with the new support in ECR.

**Comment by jahkeup** [comment]
Currently, the [fetcher implementation will not handle](https://github.com/awslabs/amazon-ecr-containerd-resolver/blob/ea0b41cd90b316189fa034e74200a95695cb0a52/ecr/fetcher.go#L48-L76) the `mediaType` that manifest lists would use. I'm going to take a good look over the involved code paths tomorrow and come back with a proposal (or two) to get manifest lists handled here.

**Comment by samuelkarp** [comment]
Fixed by https://github.com/awslabs/amazon-ecr-containerd-resolver/pull/13.
